### PR TITLE
⬆️ updating dependencies

### PR DESCRIPTION
**Pull request by LostInDarkMath**
@ElSnoMan I updated the dependencies. Tests are green on my local machine.

### CODE REVIEW

**Comment by eformo** [comment]
Can we please get this merged in with a release?  I would like to update my pytest and Faker versions in my project.

**Comment by LostInDarkMath** [comment]
@ElSnoMan Any updates on this?

**Comment by ElSnoMan** [comment]
Sorry for the delay, y'all! I'm getting this pushed up 👍🏽

**Comment by LostInDarkMath** [comment]
Thank you very much!

**Pull request merged**
