### PR TITLE
Use pathlib instead of string formatting

### PR DESCRIPTION
**Pull request by rnestler**
Using pathlib.Path should be more robust than concatenating strings
together.

### CODE REVIEW

**Review by ElSnoMan — APPROVED** [review]

**Comment by ElSnoMan** [comment]
Another great addition! Thanks for the improvements 💪🏽

**Comment by rnestler** [comment]
It looks like you accidentally reverted my changes from #247 when merging this pull request?

**Comment by ElSnoMan** [comment]
It was an accident. I was using GitHub's UI to resolve conflicts and then the page froze. I thought it kept your changes but apparently it didn't. Hence the rush on `1.15.3`

**Comment by rnestler** [comment]
Ah and you re-added it back in #250, I somehow missed that. Well no harm apart of a bit of a strange git history and me being a bit confused :wink:

**Pull request merged**
