### PR TITLE
Added timeout to test-pylenium action

### LINKED ISSUE #307: [GH Action] UI Tests sometimes fail with Selenoid
## Problem

When a test or pipeline passes sometimes and fails other times _without any changes_, we call that "flaky". Well, it seems our `test-pylenium.yml` pipeline is flaky 😢 . Here's an example:

https://github.com/ElSnoMan/pyleniumio/actions/runs/5336984960/jobs/9672430764

## Potential Solutions

When our pipeline is "flaky", it seems the last 2-3 tests fail because of a `timeout` issue. The solution may be something as simple as configuring Selenoid to have a longer timeout. Look at their docs for some ideas:

https://github.com/marketplace/actions/start-selenoid-server?version=v2

Also, it would be nice to be able to run multiple tests as the same time to speed up the Test Run time. Right now we run all of our tests sequentially because the GitHub Action container isn't very powerful, but with some optimizations to Selenoid, we might be able to run 2-4 concurrently

### PR DESCRIPTION
**Pull request by abzdel**
1. The bug
UI tests sometimes fail during CI (fixes #307)

2. Description of the Change
I added a timeout argument after selenoid starts up on the runner.

```diff
name: Start Selenoid Server
# https://github.com/marketplace/actions/start-selenoid-server?version=v2
uses: Xotabu4/selenoid-github-action@v2
+    with:
+        selenoid-start-arguments: |
+        --args "-timeout 60s"
```

3. Verification
Tested on my own branch by changing the action trigger to ensure UI tests all passed. Then changed it back to its previous state once this was validated.

4. Release Notes
N/A

New to open source, open to any suggestions on how to improve this and/or future PRs!

### CODE REVIEW

**Comment by ElSnoMan** [comment]
This is great! Thanks for taking the time to create a PR. Let's see how the pipeline(s) do 😄

**Comment by ElSnoMan** [comment]
Poop... looks like the pipeline failed in the UI Tests step. Here's the job for more details: https://github.com/ElSnoMan/pyleniumio/actions/runs/5357935823/jobs/9723194411?pr=308

It shows that the `page crashed` for one of the tests which is relatively vague for our situation. Some ideas:

* Increase the timeout to see if that stabilizes it
* See what other config options for Selenoid exist in the GH Action that we can use

> 💡 I'm open to other ideas as well because nothing is "forcing" us to use Selenoid or this specific action

**Comment by abzdel** [comment]
Sounds good, I'll start by increasing the timeout and then look for potential other options. Thanks for your time!

**Comment by abzdel** [comment]
Just wanted to check in on this - I added a commit to the PR that increased the timeout. Are there additional steps I should take?

**Comment by ElSnoMan** [comment]
@abzdel I'm super sorry for just getting to this. You will need to merge `main` into your branch and then send a new commit. If all passes, we're good to merge

**Comment by abzdel** [comment]
No worries @ElSnoMan - just merged in main and added two commits (something in CI failed on the first run, but not when I pushed again - not sure why). Please let me know if any other changes are necessary

**Pull request merged**
