### PR TITLE
update dependencies: pydantic and pytest

### PR DESCRIPTION
**Pull request by LostInDarkMath**
@ElSnoMan

### CODE REVIEW

**Comment by LostInDarkMath** [comment]
Please note that there are some breaking changes in the new version of `webdriver-manager`. I think there are some adjustments needed for the functions in `webdriver._factory.py`. I fixed only `build_chrome()` but I'm afraid that the factories for all the other browsers need fixes too. Please have a look at it before merging!

**Comment by ElSnoMan** [comment]
I'm not sure if we should pin `webdriver-manager` to `3.8.6` which seems to be working, or make it `^3.9.1`. Thoughts?

**Comment by LostInDarkMath** [comment]
> I'm not sure if we should pin `webdriver-manager` to `3.8.6` which seems to be working, or make it `^3.9.1`. Thoughts?

What are the reasons for pinning the version of `webdriver-manager`? This just makes it harder to upgrade it later to a new major version let's say. In my opinion you should try to keep your dependencies up-to-date.

**Comment by ElSnoMan** [comment]
I did more dependency updates in this PR: https://github.com/ElSnoMan/pyleniumio/actions/runs/6053820339/job/16430075115?pr=317

Moving to Selenium Manager will be best

**Comment by LostInDarkMath** [comment]
@ElSnoMan Sounds like a good idea. Thank you!

**Pull request closed without merging**
